### ISSUE TITLE
Atrybut id w pliku xml

### ISSUE THREAD

**Issue by LukaszDev** [katanisk8/KalkWin#12]
```
<KalkulatorWiniarski>
  <Owoce>
    <Owoc id="1" nazwa="Jabłka" cukry="100" kwasy="10.5" cena="1.87" />
```

Atrybut `id` dla Owoc nie jest juz potrzebny. Kod zostal zrefaktoryzowany jakis czas temu.
Mozna usunac id dla wszystkich owocow.

Id dla dodatkow nadal jest niezbedne.

**Comment by katanisk8** [comment]
done
