### ISSUE TITLE
Lista skladnikow

### ISSUE THREAD

**Issue by LukaszDev** [katanisk8/KalkWin#17]
Dodaj nowy Groupbox z ListBox w srodku.

Skopiuj kod XAML z istniejacego ListBoxa z tym ze usun checkbox, a TextBox zamien na TextBloc - tak aby zostaly tylko dwa TextBloc'ki (jeden z nazwa owocu, drugi z iloscia).

Popraw binding dla ItemSource tak aby wskazywal na Wyniki.Przepis.Skladniki

**Comment by katanisk8** [comment]
done
