### ISSUE TITLE
Jednostki

### ISSUE THREAD

**Issue by LukaszDev** [katanisk8/KalkWin#20]
W różnych zmiennch (oraz w pliku Parametry.xml) przechowujesz dane z róznymi jednostkami np. czasami w zmiennej jest wartosc w [kg], innym razem jest wartosc w [g].

Sugeruje to usystematyzowac aby zawsze w kazdej zmiennej byla wartosc wyrazona w tej samej jednostce, co ulatwi programowanie i wyeliminuje potencjalne bledy.

Oczywiscie analogicznie nalezy skorygygowac obliczenia.

Wyswietlanie to odrebna sprawa - morzesz wyswietlac w dowolnej jednosce jaka jest odpowiednia w danym miejscy (po odpowiedniem przeliczeniu z jednostki podstawowej).

**Comment by katanisk8** [comment]
Gdzie dokładnie? Nie widzę żadnego miejsca gdzie dałoby się przeliczyć na tą samą jednostkę.
