### ISSUE TITLE
Anulowanie wczytania/zapisania pliku

### ISSUE THREAD

**Issue by LukaszDev** [katanisk8/KalkWin#23]
Aktualnie klikniecie w przycisk anuluj w oknie dialogowym do wczytania/zapisania projektu powoduje bład krytyczny I zawieszenie sie programu.

Nalezy dodac opsluge przycisku Anuluj.

**Comment by katanisk8** [comment]
Dodano anulowanie przy wczytywaniu. Przy zapisywaniu nie ma problemu.
