### ISSUE TITLE
Obsluga błędów

### ISSUE THREAD

**Issue by LukaszDev** [katanisk8/KalkWin#24]
Aktualnie tylko w dwuch miejscach jest zaimplementowana obsługa błdędów / przechwytywanie wyjątków.

Należy zaimplementować obsłógę błędów we wszystkich krytycznych miejscach - w szczególności:

 - wczytywanie parametrow przy uruchomieniu programu,
 - odczytywanie / zapisywanie projektu,
 - drukowanie,
 - edytor parametrów,

**Comment by katanisk8** [comment]
done
